// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using scrapperPlanning.Data;

#nullable disable

namespace scrapperPlanning.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260124165705_InitialPlanningSchema")]
    partial class InitialPlanningSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("scrapperPlanning.Models.Entities.ClassEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AurionCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AurionLabel")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AurionCode")
                        .IsUnique();

                    b.ToTable("Class", (string)null);
                });

            modelBuilder.Entity("scrapperPlanning.Models.Entities.CourseEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AurionCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Course")
                        .HasColumnType("text");

                    b.Property<string>("Module")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AurionCode")
                        .IsUnique();

                    b.ToTable("Courses", (string)null);
                });

            modelBuilder.Entity("scrapperPlanning.Models.Entities.LecturerEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FirstName", "LastName")
                        .IsUnique();

                    b.ToTable("Lecturers", (string)null);
                });

            modelBuilder.Entity("scrapperPlanning.Models.Entities.PlanningEventClassEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ClassId")
                        .HasColumnType("bigint");

                    b.Property<long>("PlanningEventId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("PlanningEventId");

                    b.ToTable("PlanningEvents_Classes", (string)null);
                });

            modelBuilder.Entity("scrapperPlanning.Models.Entities.PlanningEventCourseEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CourseId")
                        .HasColumnType("bigint");

                    b.Property<long>("PlanningEventId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("PlanningEventId");

                    b.ToTable("PlanningEvents_Courses", (string)null);
                });

            modelBuilder.Entity("scrapperPlanning.Models.Entities.PlanningEventEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ClassName")
                        .HasColumnType("text");

                    b.Property<long>("EndTime")
                        .HasColumnType("bigint");

                    b.Property<string>("IdAurion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("IdRoom")
                        .HasColumnType("bigint");

                    b.Property<bool>("Processed")
                        .HasColumnType("boolean");

                    b.Property<long>("StartTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdAurion");

                    b.HasIndex("IdRoom");

                    b.ToTable("PlanningEvents", (string)null);
                });

            modelBuilder.Entity("scrapperPlanning.Models.Entities.PlanningEventLecturerEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("LecturerId")
                        .HasColumnType("bigint");

                    b.Property<long>("PlanningEventId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("LecturerId");

                    b.HasIndex("PlanningEventId");

                    b.ToTable("PlanningEvents_Lecturers", (string)null);
                });

            modelBuilder.Entity("scrapperPlanning.Models.Entities.PlanningEventUserEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("PlanningEventId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserUuid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlanningEventId");

                    b.HasIndex("UserUuid");

                    b.ToTable("PlanningEvents_Users", (string)null);
                });

            modelBuilder.Entity("scrapperPlanning.Models.Entities.ProfileEntity", b =>
                {
                    b.Property<Guid>("UserUuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserUuid");

                    b.HasIndex("FirstName", "LastName");

                    b.ToTable("Profiles", (string)null);
                });

            modelBuilder.Entity("scrapperPlanning.Models.Entities.RoomEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AurionCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AurionRoom")
                        .HasColumnType("text");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<int>("Floor")
                        .HasColumnType("integer");

                    b.Property<string>("Room")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AurionCode")
                        .IsUnique();

                    b.ToTable("Room", (string)null);
                });

            modelBuilder.Entity("scrapperPlanning.Models.Entities.PlanningEventClassEntity", b =>
                {
                    b.HasOne("scrapperPlanning.Models.Entities.ClassEntity", "Class")
                        .WithMany("EventLinks")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("scrapperPlanning.Models.Entities.PlanningEventEntity", "PlanningEvent")
                        .WithMany("ClassLinks")
                        .HasForeignKey("PlanningEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("PlanningEvent");
                });

            modelBuilder.Entity("scrapperPlanning.Models.Entities.PlanningEventCourseEntity", b =>
                {
                    b.HasOne("scrapperPlanning.Models.Entities.CourseEntity", "Course")
                        .WithMany("EventLinks")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("scrapperPlanning.Models.Entities.PlanningEventEntity", "PlanningEvent")
                        .WithMany("CourseLinks")
                        .HasForeignKey("PlanningEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("PlanningEvent");
                });

            modelBuilder.Entity("scrapperPlanning.Models.Entities.PlanningEventEntity", b =>
                {
                    b.HasOne("scrapperPlanning.Models.Entities.RoomEntity", "Room")
                        .WithMany("PlanningEvents")
                        .HasForeignKey("IdRoom")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Room");
                });

            modelBuilder.Entity("scrapperPlanning.Models.Entities.PlanningEventLecturerEntity", b =>
                {
                    b.HasOne("scrapperPlanning.Models.Entities.LecturerEntity", "Lecturer")
                        .WithMany("EventLinks")
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("scrapperPlanning.Models.Entities.PlanningEventEntity", "PlanningEvent")
                        .WithMany("LecturerLinks")
                        .HasForeignKey("PlanningEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lecturer");

                    b.Navigation("PlanningEvent");
                });

            modelBuilder.Entity("scrapperPlanning.Models.Entities.PlanningEventUserEntity", b =>
                {
                    b.HasOne("scrapperPlanning.Models.Entities.PlanningEventEntity", "PlanningEvent")
                        .WithMany("UserLinks")
                        .HasForeignKey("PlanningEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("scrapperPlanning.Models.Entities.ProfileEntity", "Profile")
                        .WithMany("EventLinks")
                        .HasForeignKey("UserUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanningEvent");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("scrapperPlanning.Models.Entities.ClassEntity", b =>
                {
                    b.Navigation("EventLinks");
                });

            modelBuilder.Entity("scrapperPlanning.Models.Entities.CourseEntity", b =>
                {
                    b.Navigation("EventLinks");
                });

            modelBuilder.Entity("scrapperPlanning.Models.Entities.LecturerEntity", b =>
                {
                    b.Navigation("EventLinks");
                });

            modelBuilder.Entity("scrapperPlanning.Models.Entities.PlanningEventEntity", b =>
                {
                    b.Navigation("ClassLinks");

                    b.Navigation("CourseLinks");

                    b.Navigation("LecturerLinks");

                    b.Navigation("UserLinks");
                });

            modelBuilder.Entity("scrapperPlanning.Models.Entities.ProfileEntity", b =>
                {
                    b.Navigation("EventLinks");
                });

            modelBuilder.Entity("scrapperPlanning.Models.Entities.RoomEntity", b =>
                {
                    b.Navigation("PlanningEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
