FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY scrapperPlanning.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app
COPY --from=build /app/publish ./
ENV ASPNETCORE_URLS=http://0.0.0.0:5000
EXPOSE 5000
ENTRYPOINT ["dotnet", "scrapperPlanning.dll"]
